Storing the annotation state in `with_annotation`
dolfin-adjoint/pyadjoint pull request #113
Opened 2023-09-12 08:34 UTC by Ig-dolci

## Fixes Issue:
- [Like this Issue#111](https://github.com/firedrakeproject/firedrake/issues/2824[)](https://github.com/dolfin-adjoint/pyadjoint/issues/111)

2023-09-12 08:53 UTC, connorjward requested changes

2023-09-12 08:53 UTC, connorjward commented on pyadjoint/tape.py
> +    if _annotation_enabled is False:
Use `if not _annotation_enabled`.

2023-09-12 09:06 UTC, Ig-dolci commented on pyadjoint/tape.py
> +        self._orig_annotation_enabled = False
done.

2023-09-12 09:07 UTC, Ig-dolci commented on pyadjoint/tape.py
> +    if _annotation_enabled is False:
done.

2023-09-12 09:22 UTC, Ig-dolci commented on pyadjoint/tape.py
>      return annotate
This modification breaks the firedrake tests. I think `annotate` needs to be defined anyway.

2023-09-28 08:36 UTC, dham commented on pyadjoint/tape.py
>      return annotate
I agree. @connorjward's change would change the behaviour of the function. For better or worse, the function currently has the side effect of always removing the `annotate` keyword.

2023-09-28 11:08 UTC, dham commented on pyadjoint/tape.py
> +    return _annotation_enabled
Let's not tempt fate.

2023-09-28 11:10 UTC, dham commented on .circleci/config.yml
> +            git clone --branch dham/default_annotate_on https://github.com/dolfin-adjoint/dolfin-adjoint ~/dolfin-adjoint
```suggestion
            git clone https://github.com/dolfin-adjoint/dolfin-adjoint ~/dolfin-adjoint
```

2023-09-28 11:13 UTC, merged