Fix the warnings with Constant and subfunctions.
dolfin-adjoint/pyadjoint pull request #133
Opened 2024-02-13 12:10 UTC by Ig-dolci

This PR updates the firedrake tests with the correct definitions.

- Move from `Connstant(any_value, domain=mesh)` to `Functtion(R).assign(any_value)`, where `R = FunctionSpace(mesh, "R", 0)`. 
- Move from `f.split` to `f.sub`.

2024-02-14 16:19 UTC, dham requested changes

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_disk_checkpointing.py
> +    u, v = w.sub(0), w.sub(1)
```suggestion
    u, v = w.subfunctions
```

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_projection.py
> +    assert taylor_test(rf, m, h)
Why the additional variable?

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_projection.py
> +    assert taylor_test(rf, m, h)
no additional variable.

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_reduced_functional.py
> +    assert taylor_test(Jhat, c, m) > 1.9
no additional variable.

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_solving.py
> +    bc = DirichletBC(V, bv, "on_boundary")
no additional variable.

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_solving.py
> +    bc = DirichletBC(V, bv, "on_boundary")
and here.

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_split.py
> +    w1, w2 = w.sub(0), w.sub(1)
```suggestion
    w1, w2 = w.subfunctions
```

2024-02-14 16:19 UTC, dham commented on tests/firedrake_adjoint/test_split.py
> +    assert taylor_test(rf, m, h) > 1.95
don't introduce new variables.

2024-02-15 11:31 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_reduced_functional.py
> +    expr = Function(R).assign(assemble(f**2*dx))
This test fails if I set `Function(R, val=assemble(f**2*dx))`. So, I kept `Function(R).assign(assemble(f**2*dx))`.

2024-02-15 11:33 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_projection.py
> +    assert taylor_test(rf, m, h)
done.

2024-02-15 11:33 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_projection.py
> +    assert taylor_test(rf, m, h)
done.

2024-02-15 11:33 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_reduced_functional.py
> +    assert taylor_test(Jhat, c, m) > 1.9
done.

2024-02-15 11:33 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_solving.py
> +    bc = DirichletBC(V, bv, "on_boundary")
done.

2024-02-15 11:34 UTC, Ig-dolci commented on tests/firedrake_adjoint/test_solving.py
> +    bc = DirichletBC(V, bv, "on_boundary")
done.

2024-02-16 16:22 UTC, dham approved these changes

2024-02-16 16:22 UTC, merged