Optional garbage collection and more...
dolfin-adjoint/pyadjoint pull request #187
Opened 2024-12-13 11:40 UTC by Ig-dolci

2025-01-21 11:16 UTC, Ig-dolci commented on pyadjoint/tape.py
> +            Optionally the user can provide the `generation` key. The default value
Add generation and say correctly about the key for checkpointing and the generation key.

2025-01-21 11:16 UTC, Ig-dolci commented on pyadjoint/tape.py
> +            Optionally the user can provide the `generation` key. The default value
Add two args (gc_timestep_frequency and gc_generation) instead of adding a dictionary.

2025-01-21 11:16 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                # Store the supposed global dependencies.
```suggestion
                # Store the possible global dependencies.
```

2025-01-22 10:49 UTC, jrmaddison commented
Is it equivalent to instead drop zero output `Block`s on the tape for garbage collection? Or is this slightly different?

2025-01-22 13:22 UTC, Ig-dolci commented
> Is it equivalent to instead drop zero output `Block`s on the tape for garbage collection? Or is this slightly different?

I believe it is different. I noticed that mainly during the recomputation process, memory usage kept growing, even after I cleared the checkpoint using block_variable._checkpoint = None. After some discussions here, my hypothesis is that Python might not be tracking all objects in memory properly. So, I am only allowing the user to employ the garbage collector manually, which looks like is helping.

2025-01-23 11:39 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +            if self.self._gc_time_frequency:
```suggestion
            if self._gc_time_frequency:
```

2025-01-23 11:39 UTC, Ig-dolci commented on pyadjoint/tape.py
> +
```suggestion
```

2025-01-23 11:39 UTC, Ig-dolci commented on pyadjoint/tape.py
> +                        self._checkpoint[var] = var._checkpoint
```suggestion 
                        # A new checkpoint object is not necessary here.
                        self._checkpoint[var] = var._checkpoint
```

2025-01-23 11:39 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +        self._gc_time_frequency = gc_timestep_frequency
```suggestion
        # The user can manually invoke the garbage collector if Python fails to
        # track and clean all checkpoint objects in memory properly.
        self._gc_time_frequency = gc_timestep_frequency
```

2025-01-24 12:28 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                        if not out.marked_in_path and out in current_step.adjoint_dependencies:
```suggestion
                        if not out.marked_in_path:
```

2025-02-06 11:39 UTC, connorjward commented on pyadjoint/checkpointing.py
> +        # track and clean all checkpoint objects in memory properly.
This is confusing because setting `gc_timestep_frequency` suggests that GC is being run automatically, whereas here you say manually

2025-02-06 11:41 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                deps_to_clear = self._global_deps - self._global_deps.intersection(
I think you might want `set.difference` https://docs.python.org/3/library/stdtypes.html#frozenset.difference

2025-02-06 11:42 UTC, connorjward commented on pyadjoint/checkpointing.py
> +            if timestep == 1:
I would want a big comment here explaining what is going on, perhaps even with an example. What are `_global_deps`? Why does removing `_checkpoint` do the right thing?

2025-02-06 11:45 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
I would be tempted to add a `logging.info("Running a garbage collection cycle")` or similar here. Logging is already used inside pyadjoint [here](https://github.com/dolfin-adjoint/pyadjoint/blob/da58d45c5a4dafe529e215f977e108fbabc2f360/pyadjoint/control.py#L50) for example

2025-02-06 11:45 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
possible logging as above

2025-02-06 11:45 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
logging as above

2025-02-06 11:47 UTC, connorjward commented on pyadjoint/tape.py
> +            gc_timestep_frequency (int): The timestep frequency for garbage collection.
Same docstring comment as above.

Also, why is this being repeated? It might make more sense to say: "for more information about this argument refer to :class:`CheckpointManager`"

2025-02-06 11:48 UTC, connorjward commented on pyadjoint/tape.py
> +        # from the outputs not marked in the path..
```suggestion
        # from the outputs not marked in the path.
```

2025-02-06 11:48 UTC, connorjward commented on pyadjoint/tape.py
> +            not be time-dependent and should be in the checkpointable states at every time step.
I'd love to have more detail on this.

2025-02-06 16:38 UTC, Ig-dolci commented on pyadjoint/tape.py
> +            Optionally the user can provide the `generation` key. The default value
Done.

2025-02-06 16:38 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
Done.

2025-02-06 16:39 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
Done.

2025-02-06 16:39 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                gc.collect(self._gc_generation)
Done

2025-02-06 16:45 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +        being affected by the Python fails to track and clean all checkpoint objects in memory properly.
@connorjward here are the updated docs for `gc_timestep_frequency`.

2025-02-06 16:46 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +        # and recreation of its checkpoint data.
@connorjward Here, I try to explain why ``self._global_deps`` and what is going to store.

2025-02-06 16:47 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                # global dependencies.
A complement to the docs added when the ``self._global_deps`` was created.

2025-02-06 17:24 UTC, connorjward requested changes

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                deps_to_clear = self._global_deps.difference(self._global_deps.intersection(
I don't think you need to have the `intersection` here.

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/tape.py
>                          # Create a new checkpoint object is not necessary here
```suggestion
                        # Creating a new checkpoint object is not necessary here
```

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/tape.py
> +                        # because the global dependencies do not change all the time.
```suggestion
                        # because the global dependencies do not change.
```

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                # global dependencies.
```suggestion
                # Check if the block variables stored in `self._global_deps` are still
                # dependencies in the previous timestep. If not, remove them from the
                # global dependencies.
```

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                deps_to_clear = self._global_deps.difference(self._global_deps.intersection(
But I could be wrong.

2025-02-06 17:24 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                # only in the ``self.tape.timesteps`` checkpoints when needed.
I'm afraid I don't quite understand what this means. Could you rephrase this?

2025-02-06 17:54 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                # only in the ``self.tape.timesteps`` checkpoints when needed.
Better to understand this text: 
```
For no global dependencies, checkpoint storage occurs at a ``self.tape`` timestep only when required by an action from the schedule. Thus, we have to clear the checkpoint of block variables excluded from the ``self._global_deps``.

```

2025-02-07 10:15 UTC, connorjward commented on pyadjoint/checkpointing.py
> +                # only in the ``self.tape.timesteps`` checkpoints when needed.
Yeah I think that's good. Thanks.

2025-02-11 10:59 UTC, angus-g commented
I think something that could be worth looking at here is the circular reference between `OverloadedType` and `BlockVariable`:
https://github.com/dolfin-adjoint/pyadjoint/blob/c7d73923ef77ca439311b9c044afc7e34580b54f/pyadjoint/overloaded_type.py#L96-L98

In effect, any subclass of `OverloadedType` can *only* be deleted after garbage collection, not reference counting. I think this means that several data arrays sit around for longer than they should, rather than being deleted when their owner goes out of scope.

2025-02-11 11:21 UTC, connorjward commented
> In effect, any subclass of OverloadedType can only be deleted after garbage collection, not reference counting. I think this means that several data arrays sit around for longer than they should, rather than being deleted when their owner goes out of scope.

Is there any chance that this could be made a weakref so as to avoid this cycle?

2025-02-11 11:32 UTC, dham commented
> > In effect, any subclass of OverloadedType can only be deleted after garbage collection, not reference counting. I think this means that several data arrays sit around for longer than they should, rather than being deleted when their owner goes out of scope.
> 
> Is there any chance that this could be made a weakref so as to avoid this cycle?

I think so. I think the BlockVariable should not prolong the lifetime of the Overloaded Type, so `BlockVariable.output` should be a weakref. We have to be careful that we're not abusing `Blockvariable.output` anywhere (i.e. relying on it as a source of information after the operation has been taped).

2025-02-11 11:50 UTC, Ig-dolci commented
> > In effect, any subclass of OverloadedType can only be deleted after garbage collection, not reference counting. I think this means that several data arrays sit around for longer than they should, rather than being deleted when their owner goes out of scope.
> 
> Is there any chance that this could be made a weakref so as to avoid this cycle?

I already tried weakref for `BlockVariables.output`, but I hit a number of errors I do not remember now. It is a very careful work to do.

2025-02-11 11:50 UTC, angus-g commented
I had a hacky go at that before, which worked for the forward run of the tape (with some implementation ugliness). The underlying OverloadedVarable was deleted at some point before/during the adjoint call, so that might need some care.

2025-02-11 13:50 UTC, jrmaddison commented
Looks easier to break the cycle on the other side, see #194 for an attempt.

2025-02-12 15:58 UTC, Ig-dolci commented
To make you updated:

I have tested this PR merged to the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  against the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  (**only**) for [Burgers' equation](https://github.com/dolfin-adjoint/pyadjoint/blob/master/tests/firedrake_adjoint/test_burgers_newton.py#L122) using the following setup: 40,000 DoFs and 1,000 time steps.  

The chart below uses `SingleDiskStorageSchedule`. The black line represents the results related to the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  (**only**), and the blue line represents this PR merged to the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  using `gc_timestep_frequency=100`.
![mem_gc](https://github.com/user-attachments/assets/5ee40627-eb50-434a-b9e7-c30e2f9c58c3)

2025-02-12 16:08 UTC, Ig-dolci commented
I will also check the [PR 4033](https://github.com/firedrakeproject/firedrake/pull/4033) using the same example and add it here.

2025-02-12 19:47 UTC, Ig-dolci commented
Now using  [firedrake PR 4033](https://github.com/firedrakeproject/firedrake/pull/4033) merged to [firedrake PR 4020](https://github.com/firedrakeproject/firedrake/pull/4020) that automatically uses  `SingleDiskStorageSchedule`.

Again, I have tested this PR merged to the [pyadjoint PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  against the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  (**only**) for [Burgers' equation](https://github.com/dolfin-adjoint/pyadjoint/blob/master/tests/firedrake_adjoint/test_burgers_newton.py#L122) using the following setup: 40,000 DoFs and 1,000 time steps.  

The black line represents the results related to the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  (**only**), and the blue line represents this PR merged to the [PR 194](https://github.com/dolfin-adjoint/pyadjoint/pull/194)  using `gc_timestep_frequency=100`.
![final](https://github.com/user-attachments/assets/40d6b24b-7185-4268-95af-8e382c718b4e)

2025-02-18 10:44 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +        being affected by the Python fails to track and clean all checkpoint objects in memory properly.
```suggestion
        gc_timestep_frequency (None or int): The number of timesteps between additional garbage collections. The default
        is `None`, which means no additional garbage collection. If an integer is
        provided, the garbage collector is applied every `gc_timestep_frequency` timesteps. This is useful if delays
        in object collection are causing excessive memory usage.
```

2025-02-18 10:44 UTC, Ig-dolci commented on pyadjoint/checkpointing.py
> +                deps_to_clear = self._global_deps.difference(self._global_deps.intersection(
I will check this.

2025-02-18 10:44 UTC, Ig-dolci commented on pyadjoint/tape.py
> +        if gc_timestep_frequency and not isinstance(gc_timestep_frequency, int):
```suggestion
        if gc_timestep_frequency is not None and not isinstance(gc_timestep_frequency, int):
```

2025-02-18 11:52 UTC, connorjward approved these changes
Looks great. Very readable now.

2025-02-18 11:55 UTC, merged